version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
  nextjs:
    build: .
    ports:
      - "3700:8080"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
      - .env:/app/.env
    command: npm run dev
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=strava-commute
      - REDIS_URL=redis://redis:6379
      # create a .env file in the root directory and add
      # - NEXT_PUBLIC_STRAVA_CLIENT_ID=your_client_id
      # - STRAVA_CLIENT_SECRET=your_client_secret
      - NEXT_PUBLIC_STRAVA_REDIRECT_URI=http://localhost:3700/auth/strava
      - JWT_KEY=f84a8ad8-7b3b-4b3b-8b3b-8b3b8b3b8b3b
      - JWT_EXPIRES_IN=3600
volumes:
  mongodb_data:
